package com.example.wisebite.data.model

import com.google.gson.annotations.SerializedName
import java.text.SimpleDateFormat
import java.util.*

data class SurpriseBag(
    @SerializedName("id")
    val id: String,
    
    @SerializedName("name")
    val name: String,
    
    @SerializedName("description")
    val description: String?,
    
    @SerializedName("bag_type")
    val bagType: String,
    
    @SerializedName("original_value")
    val originalValue: Double,
    
    @SerializedName("discounted_price")
    val discountedPrice: Double,
    
    @SerializedName("discount_percentage")
    val discountPercentage: Double,
    
    @SerializedName("quantity_available")
    val quantityAvailable: Int,
    
    @SerializedName("max_per_customer")
    val maxPerCustomer: Int,
    
    @SerializedName("available_from")
    val availableFrom: String,
    
    @SerializedName("available_until")
    val availableUntil: String,
    
    @SerializedName("pickup_start_time")
    val pickupStartTime: String,
    
    @SerializedName("pickup_end_time")
    val pickupEndTime: String,
    
    @SerializedName("is_active")
    val isActive: Boolean,
    
    @SerializedName("is_auto_generated")
    val isAutoGenerated: Boolean,
    
    @SerializedName("store")
    val store: Store?
) {
    // Helper properties for UI display
    val formattedOriginalPrice: String
        get() = "${String.format("%,.0f", originalValue)}đ"
    
    val formattedDiscountedPrice: String
        get() = "${String.format("%,.0f", discountedPrice)}đ"
    
    val formattedDiscountPercentage: String
        get() = "${(discountPercentage * 100).toInt()}%"
    
    val pickupTimeDisplay: String
        get() {
            return try {
                val inputFormat = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss", Locale.getDefault())
                val outputFormat = SimpleDateFormat("HH:mm", Locale.getDefault())
                val startTime = inputFormat.parse(pickupStartTime)
                val endTime = inputFormat.parse(pickupEndTime)
                "${outputFormat.format(startTime)} - ${outputFormat.format(endTime)}"
            } catch (e: Exception) {
                "Pickup time not available"
            }
        }
    
    val quantityDisplay: String
        get() = when {
            quantityAvailable <= 0 -> "Hết hàng"
            quantityAvailable == 1 -> "Còn 1 túi"
            else -> "Còn $quantityAvailable túi"
        }
    
    val categoryDisplayName: String
        get() = when (bagType) {
            "Combo" -> "Combo (Tổng hợp)"
            "Thịt/Cá" -> "Thịt/Cá"
            "Rau/Củ" -> "Rau/Củ"
            "Trái cây" -> "Trái cây"
            "Bánh mì" -> "Bánh mì"
            else -> bagType
        }
    
    val isAvailable: Boolean
        get() {
            val now = Date()
            return try {
                val inputFormat = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss", Locale.getDefault())
                val availableUntilDate = inputFormat.parse(availableUntil)
                val pickupStartDate = inputFormat.parse(pickupStartTime)
                
                isActive && 
                quantityAvailable > 0 && 
                availableUntilDate?.after(now) == true &&
                pickupStartDate?.after(Date(now.time + 5 * 60 * 1000)) == true // 5 minutes from now
            } catch (e: Exception) {
                false
            }
        }
}

data class FoodItem(
    @SerializedName("id")
    val id: String,
    
    @SerializedName("name")
    val name: String,
    
    @SerializedName("description")
    val description: String?,
    
    @SerializedName("original_price")
    val originalPrice: Double,
    
    @SerializedName("store")
    val store: Store?
)